use super::*;
use crate::{
    CommentPos, ProcessedData,
    types::{Error, RPGMFileType},
};
use rm2k::{
    field::List,
    rpg::{CommonEvent, Enemy, Item, Skill, State, Switch, Terms, Troop, Variable},
};

use super::rm2k_entity_pass;

rm2k_entity_pass!(
    /// Processes the `actors` entity list from `RPG_RT.ldb`.
    process_rm2k_actors,
    RPGMFileType::Rm2kActors,
    rm2k::rpg::Actor<'_>,
    { name, title }
);

rm2k_entity_pass!(
    /// Processes the `skills` entity list from `RPG_RT.ldb`.
    process_rm2k_skills,
    RPGMFileType::Rm2kSkills,
    Skill<'_>,
    { name, description, using_message1, using_message2 }
);

rm2k_entity_pass!(
    /// Processes the `items` entity list from `RPG_RT.ldb`.
    process_rm2k_items,
    RPGMFileType::Rm2kItems,
    Item<'_>,
    { name, description }
);

rm2k_entity_pass!(
    /// Processes the `enemies` entity list from `RPG_RT.ldb`.
    process_rm2k_enemies,
    RPGMFileType::Rm2kEnemies,
    Enemy<'_>,
    { name }
);

rm2k_entity_pass!(
    /// Processes the `classes` entity list from `RPG_RT.ldb` (RPG Maker 2003 only).
    process_rm2k_classes,
    RPGMFileType::Rm2kClasses,
    rm2k::rpg::Class<'_>,
    { name }
);

rm2k_entity_pass!(
    /// Processes the `states` entity list from `RPG_RT.ldb`.
    process_rm2k_states,
    RPGMFileType::Rm2kStates,
    State<'_>,
    { name, message_actor, message_enemy, message_already, message_affected, message_recovery }
);

impl Base {
    /// Processes the `troops` entity list from `RPG_RT.ldb`.
    ///
    /// Unlike the simple entity kinds above, a troop's name and its battle
    /// pages' event commands share one id and one output section - the same
    /// pairing `core::other::process_object`/`process_array` give MV/VX's
    /// `Troops` file - so this isn't generated by the `rm2k_entity_pass!` macro.
    pub fn process_rm2k_troops(
        &mut self,
        list: &mut List<Troop<'_>>,
        translation: Option<&str>,
    ) -> Result<Option<ProcessedData>, Error> {
        self.reset();
        self.file_type = RPGMFileType::Rm2kTroops;
        self.initialize_translation(translation)?;

        let mut processed = false;

        for troop in list.iter_mut() {
            let id = troop.id as u16;

            if self.get_translation_map(id).is_break() {
                if self.mode.is_purge() {
                    processed = true;
                }

                continue;
            }

            processed = true;

            let name_text = self.decode_with_fallback(troop.name.as_bytes());
            self.update_metadata(id, Vec::from([(CommentPos::Name, name_text.as_str())]));

            self.process_rm2k_string_field(&mut troop.name);

            for page in troop.pages.iter_mut() {
                if page.event_commands.0.is_empty() {
                    continue;
                }

                self.process_rm2k_event_list(&mut page.event_commands);
            }

            self.flush_translation(id);
        }

        if !processed {
            return Ok(None);
        }

        if self.mode.is_write() {
            Ok(None)
        } else {
            Ok(Some(self.finish_translation()))
        }
    }

    /// Processes the `commonevents` entity list from `RPG_RT.ldb`.
    ///
    /// A common event's name and its own event commands share one id and one
    /// output section, same as [`Base::process_rm2k_troops`].
    pub fn process_rm2k_commonevents(
        &mut self,
        list: &mut List<CommonEvent<'_>>,
        translation: Option<&str>,
    ) -> Result<Option<ProcessedData>, Error> {
        self.reset();
        self.file_type = RPGMFileType::Rm2kCommonEvents;
        self.initialize_translation(translation)?;

        let mut processed = false;

        for event in list.iter_mut() {
            let id = event.id as u16;

            if self.get_translation_map(id).is_break() {
                if self.mode.is_purge() {
                    processed = true;
                }

                continue;
            }

            processed = true;

            let name_text = self.decode_with_fallback(event.name.as_bytes());
            self.update_metadata(id, Vec::from([(CommentPos::Name, name_text.as_str())]));

            self.process_rm2k_string_field(&mut event.name);

            if !event.event_commands.0.is_empty() {
                self.process_rm2k_event_list(&mut event.event_commands);
            }

            self.flush_translation(id);
        }

        if !processed {
            return Ok(None);
        }

        if self.mode.is_write() {
            Ok(None)
        } else {
            Ok(Some(self.finish_translation()))
        }
    }

    /// Processes the `terms` (battle/menu/shop vocabulary) section from `RPG_RT.ldb`.
    ///
    /// `Terms` is a single struct, not a list - there is nothing to key
    /// `get_translation_map` on but one fixed id, the same one-section
    /// convention `core::system::process_system` uses for MV/VX's currency
    /// unit/game title.
    pub fn process_rm2k_terms(
        &mut self,
        terms: &mut Terms<'_>,
        translation: Option<&str>,
    ) -> Result<Option<ProcessedData>, Error> {
        self.reset();
        self.file_type = RPGMFileType::Rm2kTerms;
        self.initialize_translation(translation)?;

        const ID: u16 = 1;

        if self.get_translation_map(ID).is_break() {
            // On `Mode::Purge`, `get_translation_map` already flushed the
            // section by itself; on any other mode there's nothing to do.
            return if self.mode.is_purge() {
                Ok(Some(self.finish_translation()))
            } else {
                Ok(None)
            };
        }

        macro_rules! fields {
            ($($field:ident),* $(,)?) => {
                $( self.process_rm2k_string_field(&mut terms.$field); )*
            };
        }

        fields!(
            encounter,
            special_combat,
            escape_success,
            escape_failure,
            victory,
            defeat,
            exp_received,
            gold_recieved_a,
            gold_recieved_b,
            item_recieved,
            attacking,
            enemy_critical,
            actor_critical,
            defending,
            observing,
            focus,
            autodestruction,
            enemy_escape,
            enemy_transform,
            enemy_damaged,
            enemy_undamaged,
            actor_damaged,
            actor_undamaged,
            skill_failure_a,
            skill_failure_b,
            skill_failure_c,
            dodge,
            use_item,
            hp_recovery,
            parameter_increase,
            parameter_decrease,
            enemy_hp_absorbed,
            actor_hp_absorbed,
            resistance_increase,
            resistance_decrease,
            level_up,
            skill_learned,
            battle_start,
            miss,
            shop_greeting1,
            shop_regreeting1,
            shop_buy1,
            shop_sell1,
            shop_leave1,
            shop_buy_select1,
            shop_buy_number1,
            shop_purchased1,
            shop_sell_select1,
            shop_sell_number1,
            shop_sold1,
            shop_greeting2,
            shop_regreeting2,
            shop_buy2,
            shop_sell2,
            shop_leave2,
            shop_buy_select2,
            shop_buy_number2,
            shop_purchased2,
            shop_sell_select2,
            shop_sell_number2,
            shop_sold2,
            shop_greeting3,
            shop_regreeting3,
            shop_buy3,
            shop_sell3,
            shop_leave3,
            shop_buy_select3,
            shop_buy_number3,
            shop_purchased3,
            shop_sell_select3,
            shop_sell_number3,
            shop_sold3,
            inn_a_greeting_1,
            inn_a_greeting_2,
            inn_a_greeting_3,
            inn_a_accept,
            inn_a_cancel,
            inn_b_greeting_1,
            inn_b_greeting_2,
            inn_b_greeting_3,
            inn_b_accept,
            inn_b_cancel,
            possessed_items,
            equipped_items,
            gold,
            battle_fight,
            battle_auto,
            battle_escape,
            command_attack,
            command_defend,
            command_item,
            command_skill,
            menu_equipment,
            menu_save,
            menu_quit,
            new_game,
            load_game,
            exit_game,
            status,
            row,
            order,
            wait_on,
            wait_off,
            level,
            health_points,
            spirit_points,
            normal_status,
            exp_short,
            lvl_short,
            hp_short,
            sp_short,
            sp_cost,
            attack,
            defense,
            spirit,
            agility,
            weapon,
            shield,
            armor,
            helmet,
            accessory,
            save_game_message,
            load_game_message,
            file,
            exit_game_message,
            yes,
            no,
            maniac_item_received_a,
            maniac_level_up_a,
            maniac_level_up_b,
            maniac_level_up_c,
            maniac_exp_received_a,
            maniac_skill_learned_a,
            easyrpg_item_number_separator,
            easyrpg_skill_cost_separator,
            easyrpg_equipment_arrow,
            easyrpg_status_scene_name,
            easyrpg_status_scene_class,
            easyrpg_status_scene_title,
            easyrpg_status_scene_condition,
            easyrpg_status_scene_front,
            easyrpg_status_scene_back,
            easyrpg_order_scene_confirm,
            easyrpg_order_scene_redo,
            easyrpg_battle2k3_double_attack,
            easyrpg_battle2k3_defend,
            easyrpg_battle2k3_observe,
            easyrpg_battle2k3_charge,
            easyrpg_battle2k3_selfdestruct,
            easyrpg_battle2k3_escape,
            easyrpg_battle2k3_special_combat_back,
            easyrpg_battle2k3_skill,
            easyrpg_battle2k3_item,
        );

        self.flush_translation(ID);

        if self.mode.is_write() {
            Ok(None)
        } else {
            Ok(Some(self.finish_translation()))
        }
    }
}
